name: client

services:
  core:
    build:
      context: .
      target: development
      args:
        USERNAME: ${DEV_CONTAINER_USERNAME:-client}
        USER_UID: ${DEV_CONTAINER_UID:-1000}
        USER_GID: ${DEV_CONTAINER_GID:-1000}
    working_dir: /home/${DEV_CONTAINER_USERNAME:-client}/workspace
    volumes:
      - type: bind
        source: .
        target: /home/${DEV_CONTAINER_USERNAME:-client}/workspace
    command: sleep infinity
    tty: true
    stdin_open: true
    init: true
    user: ${DEV_CONTAINER_UID:-1000}:${DEV_CONTAINER_GID:-1000}
    environment:
      CARGO_HOME: /home/${DEV_CONTAINER_USERNAME:-client}/.cargo
    networks:
      outer:
        aliases:
          - client

networks:
  outer:
    external: true
